// Mock Data for Client Demonstration
// Set NEXT_PUBLIC_USE_MOCK_DATA=true in .env.local to enable

export const MOCK_USERS = [
  // Faculty - System Admin (kept for login)
  {
    id: 'user-009',
    full_name: 'BSMT Faculty Member',
    email: 'bsmtCogniLab2026@gmail.com',
    username: 'BSMT2026LIS',
    password: 'BSMT2026LIS', // Mock only - THIS IS THE ONLY ONE WHO CAN ENTER THE SYSTEM
    role: 'faculty',
    department: 'Laboratory Management',
    status: 'active',
    encryption_key: 'ENC_KEY_ADMIN',
    join_date: '2024-01-01',
    last_login: new Date().toISOString(),
    created_at: '2024-01-01T10:00:00Z',
    updated_at: '2024-01-01T10:00:00Z',
  },
];

export const MOCK_PATIENTS: any[] = [];

export const MOCK_TEST_RESULTS: any[] = [];

export const MOCK_BILLING: any[] = [];

// Test pricing reference
export const TEST_PRICING: Record<string, Record<string, number>> = {
  'BLOOD BANK': {
    'ABO Blood Typing': 200,
    'Rh Typing': 150,
    'Crossmatching': 300,
    'Antibody Screening': 250,
    'Infectious Disease Screening': 500,
  },
  'HEMATOLOGY': {
    'CBC': 500,
    'RBC Indices (MCV, MCH, RDW)': 400,
    'Hemoglobin': 300,
    'Neutrophils': 150,
    'Lymphocytes': 150,
    'Monocytes': 150,
    'Eosinophils': 150,
    'Basophils': 150,
    'WBC Count': 200,
    'MCV': 150,
    'MCH': 150,
    'RDW': 150,
    'Hemoglobin (Male)': 150,
    'Hemoglobin (Female)': 150,
    'Hematocrit (Male)': 150,
    'Hematocrit (Female)': 150,
    'Platelet Count': 200,
    'PT/INR/aPTT': 500,
    'PT': 250,
    'INR': 200,
    'aPTT': 250,
    'ESR (Male)': 200,
    'ESR (Female)': 200,
  },
  'CLINICAL MICROSCOPY': {
    'Routine Urinalysis (UA)': 600,
    'Routine Fecalysis (FA)': 500,
  },
  'MICROBIOLOGY': {
    'AFB Staining (Sputum/Fluid)': 300,
    'Culture and Sensitivity': 800,
    'Gram Staining': 200,
    'Pus Cells (WBCs)': 200,
    'India Ink': 250,
    'Wet Mount': 200,
    'KOH Mount': 250,
  },
  'HISTOPATHOLOGY': {
    'Kidney Biopsy': 2000,
    'Bone Biopsy': 2000,
    'Skin Biopsy': 1500,
    'Liver Biopsy Fibrosis': 2000,
    'Liver Biopsy Activity': 2000,
  },
  'IMMUNOLOGY/SEROLOGY': {
    'HBsAg (Hepa B Surface Ag) - Qualitative': 300,
    'HBsAg (Hepa B Surface Ag) - Quantitative': 400,
    'Anti-HBs (Quantitative)': 350,
    'Anti-HCV (Qualitative)': 300,
    'Anti-HCV (Quantitative)': 400,
    'Anti-HIV 1 & 2 (Qualitative)': 400,
    'Anti-HIV 1 & 2 (Quantitative)': 500,
    'Anti-Streptolysin O (ASO) - Adult': 350,
    'Anti-Streptolysin O (ASO) - Child': 350,
    'C3': 350,
    'C-Reactive Protein (CRP)': 300,
    'Dengue Duo/Blot (Ag, IgG, IgM)': 400,
    'Dengue NS1Ag': 350,
    'Leptospirosis Test': 350,
    'Rheumatoid Factor (RF)': 300,
    'Syphilis Test (Qualitative)': 300,
    'Syphilis Test (Quantitative)': 350,
    'Typhidot Test (IgG, IgM)': 350,
  },
  'CLINICAL CHEMISTRY': {
    'Random Blood Sugar (RBS)': 200,
    'Fasting Blood Sugar (FBS)': 200,
    'OGTT 75g (Normal)': 300,
    'OGTT 75g (Impaired)': 300,
    'OGTT 75g (Diabetes)': 300,
    'Hemoglobin A1c (Normal)': 350,
    'Hemoglobin A1c (Prediabetes)': 350,
    'Hemoglobin A1c (Diabetes)': 350,
    'Total Cholesterol': 250,
    'Triglycerides': 250,
    'HDL': 250,
    'LDL': 250,
    'Sodium (Na+)': 150,
    'Potassium (K+)': 150,
    'Chloride (Cl-)': 150,
    'Calcium - Total': 150,
    'Phosphorus': 150,
    'Magnesium': 150,
    'Albumin (Adults)': 200,
    'Alkaline Phosphatase (Female)': 250,
    'Alkaline Phosphatase (Male)': 250,
    'Ammonia': 300,
    'Amylase': 300,
    'Bilirubin - Direct': 200,
    'Bilirubin - Total': 200,
    'Blood Urea Nitrogen (BUN)': 200,
    'Serum Creatinine': 200,
    'Blood Uric Acid': 200,
    'CK (Female)': 300,
    'CK (Male)': 300,
    'CK-MB': 300,
    'CO2 (Bicarbonate)': 150,
    'DHEA (Female)': 350,
    'DHEA (Male)': 350,
    'Folate': 300,
    'GGT (Female)': 250,
    'GGT (Male)': 250,
    'Lactate Dehydrogenase (LDH)': 300,
    'Lipase': 300,
    'Lactic Acid': 250,
    'Serum Osmolality': 300,
    'Prealbumin': 300,
    'SGOT/AST (Female)': 250,
    'SGOT/AST (Male)': 250,
    'SGPT/ALT (Female)': 250,
    'SGPT/ALT (Male)': 250,
    'Total Protein': 200,
    'Urine Creatinine (Female - 24hr)': 300,
    'Urine Creatinine (Male - 24hr)': 300,
    'Testosterone (Male)': 400,
    'Testosterone (Female)': 400,
    'Troponin I': 350,
    'Troponin T': 350,
    'SAAG': 300,
    'Urine Sodium (Random)': 200,
    'Urine Sodium (24hr)': 250,
    'Urine Potassium (Random)': 200,
    'Urine Potassium (24hr)': 250,
    'Arterial pH': 300,
    'Arterial PCO2': 300,
    'Arterial PO2': 300,
    'Arterial SaO2': 300,
    'Arterial HCO3': 300,
    'Venous pH': 300,
    'Venous PCO2': 300,
    'Venous PO2': 300,
    'Venous SaO2': 300,
    'Venous HCO3': 300,
  },
};

// Test reference ranges
export const TEST_REFERENCE_RANGES: Record<string, Record<string, { min?: number; max?: number; normal?: string; unit: string }>> = {
  'BLOOD BANK': {
    'ABO Blood Typing': { normal: 'Type A, Type B, Type AB, or Type O', unit: '' },
    'Rh Typing': { normal: 'Rh Positive (D+) or Rh Negative (D-)', unit: '' },
    'Crossmatching': { normal: 'Compatible, Incompatible, or Least Compatible', unit: '' },
    'Antibody Screening': { normal: 'Positive or Negative', unit: '' },
    'Infectious Disease Screening': { normal: 'Non-Reactive for any infectious disease, Reactive for HIV, HBV, HCV, Syphilis, or Malaria', unit: '' },
  },
  'HEMATOLOGY': {
    'CBC': { normal: 'Neutrophils 45-75%, Lymphocytes 16-46%, Monocytes 4-11%, Eosinophils 0-8%, Basophils 0-3%', unit: '' },
    'RBC Indices (MCV, MCH, RDW)': { normal: 'MCV 80-100 fL, MCH 27-31 pg, RDW 11.5-14.5%', unit: '' },
    'Hemoglobin': { normal: 'Male 14.0-17.0 g/dL, Female 12.0-15.0 g/dL', unit: '' },
    'Neutrophils': { min: 45, max: 75, unit: '%' },
    'Lymphocytes': { min: 16, max: 46, unit: '%' },
    'Monocytes': { min: 4, max: 11, unit: '%' },
    'Eosinophils': { min: 0, max: 8, unit: '%' },
    'Basophils': { min: 0, max: 3, unit: '%' },
    'WBC Count': { min: 5.0, max: 10.0, unit: 'x10^9/L' },
    'MCV': { min: 80, max: 100, unit: 'fL' },
    'MCH': { min: 27, max: 31, unit: 'pg' },
    'RDW': { min: 11.5, max: 14.5, unit: '%' },
    'Hemoglobin (Male)': { min: 14.0, max: 17.0, unit: 'g/dL' },
    'Hemoglobin (Female)': { min: 12.0, max: 15.0, unit: 'g/dL' },
    'Hematocrit (Male)': { min: 40, max: 54, unit: '%' },
    'Hematocrit (Female)': { min: 37, max: 47, unit: '%' },
    'Platelet Count': { min: 150, max: 450, unit: 'x10^9/L' },
    'PT/INR/aPTT': { normal: 'PT 11.0-13.5 seconds, INR 0.8-1.2, aPTT 25.0-35.0 seconds', unit: '' },
    'PT': { min: 11.0, max: 13.5, unit: 'seconds' },
    'INR': { min: 0.8, max: 1.2, unit: '' },
    'aPTT': { min: 25.0, max: 35.0, unit: 'seconds' },
    'ESR (Male)': { min: 0, max: 15, unit: 'mm/hr' },
    'ESR (Female)': { min: 0, max: 15, unit: 'mm/hr' },
  },
  'CLINICAL MICROSCOPY': {
    'Routine Urinalysis (UA)': { normal: 'Color: Clear/Pale Yellow/Amber, Transparency: Clear, pH: 4.5-8.0, Protein/Glucose: Negative, Bilirubin/Ketone: Negative, Urobilinogen: 0.2-1.0, WBC: 0-5, RBC: 0-2, Bacteria/Casts/Crystals: None/Rare', unit: '' },
    'Routine Fecalysis (FA)': { normal: 'No Ova or Parasite seen, Scant/Few, Moderate, or Many/Numerous', unit: '' },
    'Fecal Occult Blood Test (FOBT)': { normal: 'Positive, Negative, or Invalid', unit: '' },
    'Pregnancy Test (PT)': { normal: 'Positive, Negative, or Invalid', unit: '' },
  },
  'MICROBIOLOGY': {
    'AFB Staining (Sputum/Fluid)': { normal: 'No Acid Fast Bacilli seen', unit: '' },
    'Culture and Sensitivity': { normal: 'Culture: Organism identification or No growth; Preliminary Report: Growth status after 24/48 hours; Final Report: Final growth status after 5-7 days; Sensitivity (Antibiogram): S (Susceptible) - The antibiotic is effective, I (Intermediate) - The antibiotic may work at higher doses, R (Resistant) - The antibiotic will not work', unit: '' },
    'Gram Staining': { normal: 'No bacteria seen or Normal Flora', unit: '' },
    'Pus Cells (WBCs)': { normal: 'Occasional, Few, Moderate, or Many', unit: '' },
    'India Ink': { normal: 'Negative (No encapsulated yeast cells seen)', unit: '' },
    'Wet Mount': { normal: 'Negative', unit: '' },
    'KOH Mount': { normal: 'Negative (No fungal elements seen)', unit: '' },
  },
  'HISTOPATHOLOGY': {
    'Kidney Biopsy': { normal: 'Normal/Unremarkable', unit: '' },
    'Bone Biopsy': { normal: 'No evidence of malignancy or Normal hematopoiesis', unit: '' },
    'Skin Biopsy': { unit: '' },
    'Liver Biopsy Fibrosis': { normal: 'F0 (No fibrosis)', unit: '' },
    'Liver Biopsy Activity': { normal: 'A0 (No inflammation)', unit: '' },
  },
  'IMMUNOLOGY/SEROLOGY': {
    'HBsAg (Hepa B Surface Ag) - Qualitative': { normal: 'Non-reactive', unit: '' },
    'HBsAg (Hepa B Surface Ag) - Quantitative': { max: 1.0, unit: 'S/CO' },
    'Anti-HBs (Quantitative)': { min: 10, normal: '≥ 10 mIU/mL (Immune/Protected)', unit: 'mIU/mL' },
    'Anti-HCV (Qualitative)': { normal: 'Non-reactive', unit: '' },
    'Anti-HCV (Quantitative)': { max: 1.0, unit: 'Index' },
    'Anti-HIV 1 & 2 (Qualitative)': { normal: 'Non-reactive', unit: '' },
    'Anti-HIV 1 & 2 (Quantitative)': { max: 1.0, unit: 'S/CO' },
    'Anti-Streptolysin O (ASO) - Adult': { max: 200, unit: 'IU/mL' },
    'Anti-Streptolysin O (ASO) - Child': { max: 150, unit: 'IU/mL' },
    'C3': { min: 80, max: 160, unit: 'mg/dL' },
    'C-Reactive Protein (CRP)': { min: 0, max: 10, unit: 'mg/L' },
    'Dengue Duo/Blot (Ag, IgG, IgM)': { normal: 'Non-reactive (IgM = Recent; IgG = Past infection)', unit: '' },
    'Dengue NS1Ag': { normal: 'Non-reactive (Detects early infection)', unit: '' },
    'Leptospirosis Test': { normal: 'Non-reactive', unit: '' },
    'Rheumatoid Factor (RF)': { max: 14, unit: 'IU/mL' },
    'Syphilis Test (Qualitative)': { normal: 'Non-reactive (Usually RPR or VDRL)', unit: '' },
    'Syphilis Test (Quantitative)': { normal: 'Non-reactive or 1:2 (Titer depends on the stage)', unit: '' },
    'Typhidot Test (IgG, IgM)': { normal: 'Non-reactive', unit: '' },
  },
  'CLINICAL CHEMISTRY': {
    'Random Blood Sugar (RBS)': { max: 140, unit: 'mg/dL' },
    'Fasting Blood Sugar (FBS)': { min: 70, max: 110, unit: 'mg/dL' },
    'OGTT 100g (Normal)': { max: 140, unit: 'mg/dL' },
    'OGTT 75g (Impaired)': { min: 140, max: 199, unit: 'mg/dL' },
    'OGTT 75g (Diabetes)': { min: 200, unit: 'mg/dL' },
    'Hemoglobin A1c (Normal)': { max: 5.7, unit: '%' },
    'Hemoglobin A1c (Prediabetes)': { min: 5.7, max: 6.4, unit: '%' },
    'Hemoglobin A1c (Diabetes)': { min: 6.5, unit: '%' },
    'Total Cholesterol': { max: 200, unit: 'mg/dL' },
    'Triglycerides': { min: 40, max: 150, unit: 'mg/dL' },
    'HDL': { min: 60, unit: 'mg/dL' },
    'LDL': { max: 100, unit: 'mg/dL' },
    'Sodium (Na+)': { min: 135, max: 145, unit: 'mmol/L' },
    'Potassium (K+)': { min: 3.4, max: 5.0, unit: 'mmol/L' },
    'Chloride (Cl-)': { min: 95, max: 108, unit: 'mmol/L' },
    'Calcium - Total': { min: 8.5, max: 10.5, unit: 'mg/dL' },
    'Phosphorus': { min: 3.0, max: 4.5, unit: 'mmol/L' },
    'Magnesium': { min: 1.8, max: 3.0, unit: 'mmol/L' },
    'Albumin (Adults)': { min: 3.5, max: 5.0, unit: 'g/dL' },
    'Alkaline Phosphatase (Female)': { min: 30, max: 100, unit: 'U/L' },
    'Alkaline Phosphatase (Male)': { min: 45, max: 115, unit: 'U/L' },
    'Ammonia': { min: 15, max: 45, unit: 'mcg/dL' },
    'Amylase': { min: 53, max: 123, unit: 'U/L' },
    'Bilirubin - Direct': { min: 0.0, max: 0.4, unit: 'mg/dL' },
    'Bilirubin - Total': { min: 0.0, max: 1.0, unit: 'mg/dL' },
    'Blood Urea Nitrogen (BUN)': { min: 8, max: 23, unit: 'mg/dL' },
    'Serum Creatinine': { min: 0.7, max: 1.3, unit: 'mg/dL' },
    'Blood Uric Acid': { min: 4, max: 8, unit: 'mg/dL' },
    'CK (Female)': { min: 40, max: 150, unit: 'U/L' },
    'CK (Male)': { min: 60, max: 400, unit: 'U/L' },
    'CK-MB': { max: 5, unit: '% of total CK' },
    'CO2 (Bicarbonate)': { min: 20, max: 32, unit: 'mmol/L' },
    'DHEA (Female)': { min: 130, max: 980, unit: 'ng/dL' },
    'DHEA (Male)': { min: 180, max: 1250, unit: 'ng/dL' },
    'Folate': { min: 3.1, max: 17.5, unit: 'ng/mL' },
    'GGT (Female)': { min: 0, max: 45, unit: 'U/L' },
    'GGT (Male)': { min: 0, max: 65, unit: 'U/L' },
    'Lactate Dehydrogenase (LDH)': { min: 0, max: 270, unit: 'U/L' },
    'Lipase': { min: 31, max: 186, unit: 'U/L' },
    'Lactic Acid': { min: 0.5, max: 2.2, unit: 'mmol/L' },
    'Serum Osmolality': { min: 275, max: 295, unit: 'mOsm/kg' },
    'Prealbumin': { min: 19.5, max: 35.8, unit: 'mg/dL' },
    'SGOT/AST (Female)': { min: 9, max: 25, unit: 'U/L' },
    'SGOT/AST (Male)': { min: 10, max: 40, unit: 'U/L' },
    'SGPT/ALT (Female)': { min: 7, max: 30, unit: 'U/L' },
    'SGPT/ALT (Male)': { min: 10, max: 55, unit: 'U/L' },
    'Total Protein': { min: 6.4, max: 8.3, unit: 'g/dL' },
    'Urine Creatinine (Female - 24hr)': { min: 0.6, max: 1.8, unit: 'g/day' },
    'Urine Creatinine (Male - 24hr)': { min: 0.8, max: 2.4, unit: 'g/day' },
    'Testosterone (Male)': { min: 270, max: 1070, unit: 'ng/dL' },
    'Testosterone (Female)': { min: 6, max: 86, unit: 'ng/dL' },
    'Troponin I': { min: 0, max: 0.4, unit: 'ng/mL' },
    'Troponin T': { min: 0, max: 0.01, unit: 'ng/mL' },
    'SAAG': { max: 1.1, unit: 'g/dL' },
    'Urine Sodium (Random)': { min: 20, unit: 'mEq/L' },
    'Urine Sodium (24hr)': { min: 40, max: 220, unit: 'mEq/L' },
    'Urine Potassium (Random)': { min: 20, unit: 'mEq/L' },
    'Urine Potassium (24hr)': { min: 25, max: 125, unit: 'mEq/day' },
    'Arterial pH': { min: 7.35, max: 7.45, unit: '' },
    'Arterial PCO2': { min: 35, max: 45, unit: 'mm Hg' },
    'Arterial PO2': { min: 80, max: 100, unit: 'mm Hg' },
    'Arterial SaO2': { min: 90, unit: '%' },
    'Arterial HCO3': { min: 22, max: 26, unit: 'mEq/L' },
    'Venous pH': { min: 7.31, max: 7.41, unit: '' },
    'Venous PCO2': { min: 40, max: 52, unit: 'mm Hg' },
    'Venous PO2': { min: 30, max: 50, unit: 'mm Hg' },
    'Venous SaO2': { min: 60, max: 75, unit: '%' },
    'Venous HCO3': { min: 21, max: 28, unit: 'mEq/L' },
  },
};

export const MOCK_AUDIT_LOGS: any[] = [];

export const MOCK_AUTH_USER = {
  id: 'user-001',
  email: 'maria.santos@lis.com',
  full_name: 'Dr. Maria Santos',
  role: 'faculty',
  department: 'Clinical Chemistry',
  encryption_key: 'ENC_KEY_001',
};
